# Generated by Django 2.2.4 on 2019-11-01 00:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('status', models.BooleanField(default=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('critical', 'CRITICAL'), ('debug', 'DEBUG'), ('error', 'ERROR'), ('warning', 'WARNING'), ('info', 'INFO')], max_length=20)),
                ('description', models.TextField()),
                ('code_error', models.IntegerField()),
                ('environment', models.CharField(choices=[('desenvolvimento', 'DEV'), ('homologacao', 'HOMOLOGAÇÃO'), ('producao', 'PRODUÇÃO')], max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'ATIVO'), ('inativo', 'INATIVO'), ('arquivado', 'ARQUIVADO')], default='ativo', max_length=20)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
